# NEXUS AI System Configuration

nexus_core:
  version: 1.0
  log_level: INFO
  max_agents: 10

router:
  strategy: smart
  fallback_enabled: true

specialists:
  enabled:
    - builder
    - coder
    - gardener

protocol:
  aicl_version: 1.0 
llm:
  provider: openai  # Options: openai, anthropic
  model: gpt-3.5-turbo  # Default for OpenAI, can be changed
  temperature: 0.7
  max_tokens: 512
  # API keys are read from environment variables: OPENAI_API_KEY or ANTHROPIC_API_KEY 